import house from "./assets/images/house.png";
import house2 from "./assets/images/house2.png";
import user from "./assets/images/user.png";
import user2 from "./assets/images/user2.png";
import beds from "./assets/icons/beds-icon.svg";
import garaga from "./assets/icons/garage-icon.svg";
import baths from "./assets/icons/baths-icon.svg";
import ruler from "./assets/icons/ruler-icon.svg";
import like from "./assets/icons/like-icon.svg";
import top from "./assets/icons/icon-top.svg";
import bottom from "./assets/icons/icon-bottom.svg";


export const cardObj = [
  {
    id: 1,
    img: house,
    title: "Uzbekistan",
    city: "Fargona",
    description: "yevro remont",
    userImg: user,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "4",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1333",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 2,
    img: house2,
    title: "Qirgistan",
    city: "Toshkent",
    description: "oila uchun",
    userImg: user2,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "3",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1290",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 3,
    img: house,
    title: "Uzbekistan",
    city: "Andijon",
    description: "o'quvchi qizlar uchun",
    userImg: user,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "5",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1900",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 4,
    img: house2,
    title: "Rossiya",
    city: "Xorazm",
    description: "sheriklikka o'gil bollar",
    userImg: user2,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "2",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1160",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 5,
    img: house,
    title: "Uzbekistan",
    city: "Samarqand",
    description: "yevro remont",
    userImg: user,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "4",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1222",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 6,
    img: house2,
    title: "USA",
    city: "Buxoro",
    description: "oila uchun",
    userImg: user2,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "3",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1330",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 7,
    img: house,
    title: "Uzbekistan",
    city: "Qoqon",
    description: "vaqtinchalik ijara",
    userImg: user,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "5",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1290",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 8,
    img: house2,
    title: "Tojikiston",
    city: "Namangan",
    description: "faqat qizlar uchun",
    userImg: user2,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "4",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1240",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 9,
    img: house,
    title: "Uzbekistan",
    city: "Sirdaryo",
    description: "ishlaydigonlar uchun",
    userImg: user,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "6",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1150",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 10,
    img: house2,
    title: "Turkiya",
    city: "Surxandaryo",
    description: "yevro remont",
    userImg: user2,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "2",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1205",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 11,
    img: house,
    title: "Uzbekistan",
    city: "Qashqadaryo",
    description: "tamir talab",
    userImg: user,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "3",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1250",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 12,
    img: house2,
    title: "Hindiston",
    city: "Navoiy",
    description: "studentlar uchun",
    userImg: user2,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "2",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1100",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 13,
    img: house,
    title: "Uzbekistan",
    city: "Fergana",
    description: "abutrentlar uchun",
    userImg: user,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "4",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1400",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 14,
    img: house2,
    title: "Xitoy",
    city: "Qoraqalpogiston",
    description: "chet elliklar uchun",
    userImg: user2,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "5",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1200",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
  {
    id: 15,
    img: house,
    title: "Uzbekistan",
    city: "Toshkent",
    description: "kunilik ijara",
    userImg: user,
    icon1: beds,
    icon2: baths,
    icon3: garaga,
    icon4: ruler,
    iconTitle1: "3",
    iconTitle2: "5 Baths",
    iconTitle3: "1 Garage",
    iconTitle4: "1300",
    price1: "$2,800/mo",
    price2: "$7,500/mo",
    topIcon: top,
    bottomIcon: bottom,
    like: like,
  },
];
